server:
  port: 8080
spring:
  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      authorizationserver:
        client:
          crm-client:
            require-authorization-consent: true
            registration:
              client-id: crm
              client-secret: "{bcrypt}$2a$10$lHEIhOIZBybWCzRZOVuko.rFe9oGBtGHnRAU97wgvJZmWQWvkBIm6"
              authorization-grant-types: client_credentials,authorization_code,refresh_token
              redirect-uris: http://127.0.0.1:8082/login/oauth2/code/my-client
              scopes: user.read,user.write,openid
              client-authentication-methods: client_secret_basic
    datasource:
      url: jdbc:postgresql://localhost/postgres
      username: postgres
      password: password



logging.level.org.springframework.security: TRACE
